// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aklluoklrtioagcygapd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbGx1b2tscnRpb2FnY3lnYXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTk4MDAsImV4cCI6MjA2Nzc5NTgwMH0.QJVNU6DKJJ76tK-vHBPhVo1DdjBbhL4Fz01_vTDpMjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});